version: '3'
services:
  homework-service:
    container_name: homework-service
    image: sureshkamboj2k16/homework-service
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: >-
        {
          "server.port": "$SPRING_DOCKER_PORT",
          "spring.datasource.url": "jdbc:mysql://docker-mysql:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC",
          "spring.datasource.username": "$MYSQLDB_USER",
          "spring.datasource.password": "$MYSQLDB_ROOT_PASSWORD",
          "spring.jpa.hibernate.ddl-auto": "$DB_DDL_AUTO"
        }
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    env_file: ./.env
    stdin_open: true
    tty: true
    depends_on:
      - docker-mysql

  docker-mysql:
    container_name: docker-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_ROOT_HOST: '%'
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    healthcheck:
      test: "/usr/bin/mysql --user=$MYSQLDB_USER --password=$MYSQLDB_ROOT_PASSWORD --execute \"SHOW DATABASES \""
      interval: 4s
      timeout: 20s
      retries: 5
